# Generated by Django 5.1 on 2024-09-06 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='civil_certificate_type',
        ),
        migrations.RemoveField(
            model_name='profileaddress',
            name='resident_comprovation',
        ),
        migrations.AddField(
            model_name='educationalinstitutionaddress',
            name='address_comprovation',
            field=models.FileField(blank=True, help_text='Faça upload do comprovante de endereço do convênio (ex: conta de luz, água, etc.). Formatos aceitos: PDF, JPG, PNG.', null=True, upload_to='convention_address_comprovations/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Comprovante de Endereço'),
        ),
        migrations.AddField(
            model_name='profileaddress',
            name='address_comprovation',
            field=models.FileField(blank=True, help_text='Faça upload do comprovante de endereço do convênio (ex: conta de luz, água, etc.). Formatos aceitos: PDF, JPG, PNG.', null=True, upload_to='convention_address_comprovations/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Comprovante de Endereço'),
        ),
        migrations.AlterField(
            model_name='convention',
            name='contract_convention',
            field=models.FileField(blank=True, help_text='Faça upload do contrato de convênio. Apenas formato PDF é aceito.', null=True, upload_to='convention_contracts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Contrato de Convênio'),
        ),
        migrations.AlterField(
            model_name='conventionaddress',
            name='address_comprovation',
            field=models.FileField(blank=True, help_text='Faça upload do comprovante de endereço do convênio (ex: conta de luz, água, etc.). Formatos aceitos: PDF, JPG, PNG.', null=True, upload_to='convention_address_comprovations/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Comprovante de Endereço'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='document',
            field=models.FileField(help_text='Faça upload do documento de identificação (formatos aceitos: pdf, jpg, png).', upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Faça upload de uma foto do perfil (formatos aceitos: jpg, png).', null=True, upload_to='profile_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='promoter',
            name='contract_promoter',
            field=models.FileField(blank=True, help_text='Faça upload do contrato de acordo com o promotor. Apenas formato PDF é aceito.', null=True, upload_to='promoter_contracts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Contrato do Promotor'),
        ),
    ]
