# Generated by Django 5.1 on 2024-09-06 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='civil_certificate',
            field=models.FileField(blank=True, help_text='Faça upload da certidão de nascimento, casamento ou divórcio. Formatos aceitos: PDF, JPG, PNG.', null=True, upload_to='civil_certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Certidão Civil'),
        ),
    ]
